describe(`Navigate the matchlisting page`,()=>{
    const matchSel = require('../../selectors/matchPlus.sel')
    beforeEach(()=>{
        cy.visit(Cypress.env("uiUrl"))
    })
    it(`Check functionality of single & multiple match & whole season selection`,()=>{
        cy.get('#Westerlo-vs-Clubbrugge-6-aug-23').check({force: true}).should("be.checked")
        cy.get('#union-vs-club-4june2023').check({force: true}).should("be.checked")
        cy.get('.btn-fixed > :nth-child(1)').click()
        cy.get(`:nth-child(1) ${matchSel.eventTitle}`).should("have.contain","Goals")
        cy.get('#goal').check({force: true}).should("be.checked")
        cy.get(`:nth-child(2) ${matchSel.eventTitle}`).should("have.contain","Penalties")
        cy.get('#penalty').check({force: true}).should("be.checked")
        cy.get(`:nth-child(3) ${matchSel.eventTitle}`).should("have.contain","Shots")
        cy.get('#target').check({force: true}).should("be.checked")
        cy.get(`:nth-child(4) ${matchSel.eventTitle}`).should("have.contain","Shots on Target")
        cy.get('#shottarget').should("not.be.checked")
        cy.get(`:nth-child(5) ${matchSel.eventTitle}`).should("have.contain","Skill")
        cy.get('#skill').should("not.be.checked")
        cy.get(`:nth-child(6) ${matchSel.eventTitle}`).should("have.contain","Saves/Blocks")
        cy.get('#save').should("not.be.checked")
        cy.get(`:nth-child(7) ${matchSel.eventTitle}`).should("have.contain","Near Misses")
        // cy.get('#big chance')
        cy.get(`:nth-child(8) ${matchSel.eventTitle}`).should("have.contain","Close Range Shots")
        cy.get('#close').should("not.be.checked")
        cy.get(`:nth-child(9) ${matchSel.eventTitle}`).should("have.contain","Mid Range Shots")
        cy.get('#mid').should("not.be.checked")
        cy.get(`:nth-child(10) ${matchSel.eventTitle}`).should("have.contain","Long Range Shots")
        cy.get('#longrange').should("not.be.checked")
        cy.get(`:nth-child(11) ${matchSel.eventTitle}`).should("have.contain","Direct Freekicks")
        cy.get('#directkick').should("not.be.checked")
        cy.get(`:nth-child(12) ${matchSel.eventTitle}`).should("have.contain","Corners")
        cy.get('#corner').should("not.be.checked")
        cy.get(`:nth-child(13) ${matchSel.eventTitle}`).should("have.contain","Crosses")
        cy.get('#crosses').should("not.be.checked")
        cy.get(`:nth-child(14) ${matchSel.eventTitle}`).should("have.contain","Offside")
        cy.get('#offside').should("not.be.checked")
        cy.get(`:nth-child(15) ${matchSel.eventTitle}`).should("have.contain","Tackles")
        cy.get('#tackle').should("not.be.checked")
        // cy.get(`:nth-child(16) ${matchSel.eventTitle}`).should("have.contain","Throw-ins")
        // cy.get('#throwin')
        cy.get(`:nth-child(16) ${matchSel.eventTitle}`).should("have.contain","Fouls")
        cy.get('#foul').should("not.be.checked")
        cy.get(`:nth-child(17) ${matchSel.eventTitle}`).should("have.contain","Cards")
        cy.get('#card').should("not.be.checked")
        cy.get(`:nth-child(18) ${matchSel.eventTitle}`).should("have.contain","Chances Created")
        cy.get('#assisted').should("not.be.checked")
        cy.get(`:nth-child(19) ${matchSel.eventTitle}`).should("have.contain","VAR")
        cy.get('#var').should("not.be.checked")
        cy.get(`:nth-child(20) ${matchSel.eventTitle}`).should("have.contain","Passes")
        cy.get('#passes').should("not.be.checked")
        cy.get(`:nth-child(21) ${matchSel.eventTitle}`).should("have.contain","Substitutions")
        cy.get('#substitution').should("not.be.checked")
        cy.get('.btn-fixed > :nth-child(2)').should("have.contain","Play Video").click()
        // cy.get('.btn-fixed > :nth-child(1)').should("have.contain","Back").click()
    })
  })